Description: >
  Membuat EC2 baru dengan settingan minimal.

Resources:
# Buat EC2 instance dengan pilihan AMI, InstanceType, UserData dan Tag.
  DemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04902260ca3d33422
      InstanceType: t3.micro
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><head><title>Hello Word</title></head><body><h1>Hello Cloudformation!</h1></body></html>" > /var/www/html/index.html
      Tags: 
      - Key: "Name"
        Value: "DemoEC2"
      - Key: "OS"
        Value: "Amazon Linux 2"