Description: >
  Membuat EC2 baru dengan settingan minimal.

Resources:
# Buat EC2 instance dengan pilihan AMI, InstanceType, UserData dan Tag.
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04902260ca3d33422
      InstanceType: t3a.micro
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y php7.2
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
      Tags: 
      - Key: Name
        Value: MyEC2
      - Key: OS
        Value: Amazon Linux 2

# Ekstrak informasi EC2 instance yang dibuat.
Outputs:
  EC2PublicDNS:
    Description: Public DNS Endpoint of EC2
    Value: !GetAtt EC2.PublicDnsName
  EC2PublicIP:
    Description: Public IPv4 of EC2
    Value: !GetAtt EC2.PublicIp
  EC2PrivateIP:
    Description: Private IPv4 of EC2
    Value: !GetAtt EC2.PrivateIp