Description: >
  Membuat Linux EC2 baru dengan Parameter (untuk InstanceType, SubnetID dan SSH Keypair) dan Mapping (untuk AMI ID).

#----------------------------------------------------------------------------------------#
Mappings:
# Daftar AMI yang akan digunakan oleh EC2 instance jika dieksekusi di Region yang berbeda.
  RegionMap:
    us-east-1:
      AmazonLinux: ami-04902260ca3d33422
    us-west-1: 
      AmazonLinux: ami-0d5075a2643fdf738
    eu-west-1: 
      AmazonLinux: ami-09ce2fc392a4c0fbc
    ap-southeast-1: 
      AmazonLinux: ami-03326c3f2f37e56a4
    ap-northeast-1: 
      AmazonLinux: ami-0404778e217f54308

#----------------------------------------------------------------------------------------#
Parameters:
# User memilih InstanceType yang nanti digunakan oleh EC2 instance, atau bisa menggunakan default value.
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t3.micro.

# User memilih Subnet untuk EC2 instance.
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select existing Subnet for EC2.

# User memilih SSH Keypair untuk remote ke EC2 instance.
  SSHKeypair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

#----------------------------------------------------------------------------------------#
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI sesuai dengan Region dimana CloudFormation template ini dieksekusi.
      ImageId:
        Fn::FindInMap: [RegionMap, Ref: AWS::Region, AmazonLinux]
# Gunakan InstanceType yang dipilih oleh User.
      InstanceType:
        Ref: InstanceType
# Gunakan Subnet yang dipilih oleh User.
      SubnetId:
        Ref: SubnetID
# Gunakan SSH Keypair yang dipilih oleh User.
      KeyName:
        Ref: SSHKeypair
      UserData:
# Mengambil data dari Instance Metadata dan memasukkan data kedalam halaman html.
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          export InstanceID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          export PrivateIP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
          export Hostname=$(curl -s http://169.254.169.254/latest/meta-data/hostname)
          echo "
            <html>
              <head><title>EC2 Home</title></head>
              <body>
                <h1>Hello $InstanceID </h1>
                <h3>Private IP: $PrivateIP </h3>
                <h3>Hostname: $Hostname </h3>
              </body>
            </html>" > /var/www/html/index.html
          echo "
            <html>
              <head><title>EC2 Health</title></head>
              <body>
                <h1>EC2 is healthy</h1>
              </body>
            </html>" > /var/www/html/health.html
      Tags:
      - Key: Name
        Value: MyEC2
      - Key: OS
        Value: Amazon Linux 2

#----------------------------------------------------------------------------------------#
Outputs:
# Ekstrak informasi EC2 instance yang dibuat. Yang perlu diperhatikan ketika EC2 instance dimatikan, maka public IPv4 atau public DNS-nya akan tidak berlaku lagi karena dua-duanya akan berubah saat EC2-nya dihidupkan kembali.
  EC2PublicDNS:
    Value:
      Fn::GetAtt: EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2

  EC2PublicIP:
    Value:
      Fn::GetAtt: EC2.PublicIp
    Description: Public IPv4 of EC2

  EC2PrivateIP:
    Value:
      Fn::GetAtt: EC2.PrivateIp
    Description: Private IPv4 of EC2