Description: >
  Linux EC2 dengan parameter dan mapping.

#----------------------------------------------------------------------------------------#
Mappings:
# Daftar AMI yang akan digunakan oleh EC2 instance jika dieksekusi di region yang berbeda. Jadi tempate ini berlaku dibeberapa region yang ada didalam daftar.
  RegionMap:
    us-east-1:
      AmazonLinux: ami-0aa7d40eeae50c9a9 # US East (N. Virginia).
    eu-central-1:
      AmazonLinux: ami-06c39ed6b42908a36 # Europe (Frankfurt).
    ap-southeast-1:
      AmazonLinux: ami-0753e0e42b20e96e3 # Asia Pacific (Singapore).
    ap-southeast-3:
      AmazonLinux: ami-0da2d702dc1ff462f # Asia Pacific (Jakarta).

#----------------------------------------------------------------------------------------#
Parameters:
# User memilih instance type yang nanti digunakan oleh EC2 instance, atau bisa menggunakan default value.
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t3.micro.

# User memilih subnet untuk EC2 instance.
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select existing Subnet for EC2.

#----------------------------------------------------------------------------------------#
Resources:
# Buat EC2 instance dengan pilihan AMI, instance type, subnet ID, keypair, user data, dan tag. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html.
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI sesuai dengan region dimana CloudFormation template ini dieksekusi.
      ImageId:
        Fn::FindInMap: [RegionMap, Ref: AWS::Region, AmazonLinux]
# Gunakan instance type yang dipilih oleh user.
      InstanceType:
        Ref: InstanceType
# Gunakan subnet yang dipilih oleh user.
      SubnetId:
        Ref: SubnetID
      UserData:
# Mengambil data dari instance metadata (http://169.254.169.254/latest/meta-data/). Lalu membuat halaman html dengan data yang diambil dari instance metadata.
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          export InstanceID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          export PrivateIP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
          export Hostname=$(curl -s http://169.254.169.254/latest/meta-data/hostname)
          echo "
            <html>
              <head><title>EC2 Home</title></head>
              <body>
                <h1>Hello $InstanceID </h1>
                <h3>Private IP: $PrivateIP </h3>
                <h3>Hostname: $Hostname </h3>
              </body>
            </html>" > /var/www/html/index.html
          echo "
            <html>
              <head><title>EC2 Health</title></head>
              <body>
                <h1>EC2 is healthy</h1>
              </body>
            </html>" > /var/www/html/health.html
      Tags:
      - Key: Name
        Value: MyEC2
      - Key: OS
        Value: Amazon Linux 2

#----------------------------------------------------------------------------------------#
Outputs:
  EC2ID:
    Value:
      Ref: EC2
    Description: EC2 ID

  EC2PrivateIP:
    Value:
      Fn::GetAtt: EC2.PrivateIp
    Description: Private IPv4 of EC2

# Ekstrak informasi public DNS dan public IPv4 address milik EC2 instance. Yang perlu diperhatikan ketika EC2 instance dimatikan, maka public DNS maupun IPv4-nya tidak akan berlaku lagi. Hal ini karena dua-duanya bersifat ephemeral atau berubah saat EC2-nya dihidupkan kembali.
  EC2PublicDNS:
    Value:
      Fn::GetAtt: EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2

  EC2PublicIP:
    Value:
      Fn::GetAtt: EC2.PublicIp
    Description: Public IPv4 of EC2