Description: >
  Membuat Linux EC2 baru dengan SecurityGroup dan ElasticIP. EC2 juga akan menggunakan Parameter (untuk InstanceType dan SSH Keypair) dan Mapping (untuk AMI ID).

#----------------------------------------------------------------------------------------#
Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t3.micro.

  SSHKeypair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

#----------------------------------------------------------------------------------------#
Resources:
# Buat EC2 instance dengan pilihan AMI, instance type, security group, keypair, user data, dan tag.
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI ID milik Amazon Linux 2 terbaru yang diambil dari System Manager - Parameter Store yang disediakan oleh AWS.
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType:
        Ref: InstanceType
# Pasang SecurityGroup yang dibuat ke EC2 instance.
      SecurityGroups:
        - Ref: SecurityGroup
      KeyName:
        Ref: SSHKeypair
      UserData:
# Download dan extract halaman website kedalam EC2 instance.
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y php7.2
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          cd /var/www/html
          wget https://furqonmauladani.s3.amazonaws.com/package.zip
          unzip package.zip
          rm -f package.zip
      Tags: 
      - Key: Name
        Value: MyEC2
      - Key: OS
        Value: Amazon Linux 2

# Buat ElasticIP dan pasang ke EC2 instance. Public IPv4 address ini tidak akan berubah meskipun EC2 instance-nya dimatikan lalu dihidupkan.
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: EC2
      Tags: 
      - Key: Name
        Value: MyEIP

# Buat SecurityGroup yang membolehkan akses HTTP, SSH, and ICMP(ping) untuk semua IP address.
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all IP address to HTTP, SSH, and ICMP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: MySecurityGroup

#----------------------------------------------------------------------------------------#
Outputs:
  EC2ID:
    Value:
      Ref: EC2
    Description: EC2 ID

  EC2PrivateIP:
    Value:
      Fn::GetAtt: EC2.PrivateIp
    Description: Private IPv4 of EC2

# Ekstrak informasi public DNS dan public IPv4 address. Public DNS dan IPv4-nya tetap berlaku, meskipun EC2-nya dihidupkan kembali. Hal ini karena EC2 instance menggunakan ElasticIP yang sifatnya static.
  EC2PublicDNS:
    Value:
      Fn::GetAtt: EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2

  EC2PublicIP:
    Value:
      Fn::GetAtt: EC2.PublicIp
    Description: Public IPv4 of EC2