Description: >
  Membuat EC2 baru dengan parameter instance type dan SSH keypair.

Parameters:
# User harus memilih InstanceType yang nanti digunakan oleh EC2 instance.
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
    Description: Enter instance type for EC2 instance. Default value is t3.micro.

# User harus memilih SSH Keypair untuk remote ke EC2 instance.
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

Resources:
  DemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04902260ca3d33422
# Gunakan InstanceType yang dipilih oleh User.
      InstanceType:
        !Ref InstanceTypeParameter
# Gunakan SSH Keypair yang dipilih oleh User.
      KeyName:
        !Ref SSHKey
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><head><title>Hello Word</title></head><body><h1>Hello Cloudformation!</h1></body></html>" > /var/www/html/index.html
      Tags: 
      - Key: "Name"
        Value: "DemoEC2-Parameter"
      - Key: "OS"
        Value: "Amazon Linux 2"