Description: >
  EC2 Amazon Linux 2 yang terdaftar di System Manager.

#----------------------------------------------------------------------------------------#
Parameters:
# User memilih System Manager - Parameter Store yang berisi AMI ID untuk EC2 instance, atau bisa menggunakan public Parameter Store yang berisi AMI ID Amazon Linux 2 terbaru. Harap gunakan AMI seperti Amazon Linux 2 yang sudah memiliki SSM agent terpasang didalamnya.
  AMI:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Select the Linux AMI ID inside System Manager - Parameter Store (The default value is the latest Amazon Linux 2 in public Parameter Store).

  InstanceType:
    Type: String
    Default: t3a.micro
    AllowedValues:
      - t3a.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t3a.micro.

  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select existing Subnet for EC2 instance.

  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select existing SecurityGroup for EC2 instance.

# User memasukkan nama EC2 yang akan digunakan melalui tag.
  EC2Name:
    Type: String
    Default: MyEC2
    Description: Enter the name for EC2 instance.

# User memasukkan URL lokasi dimana package aplikasi berada. Silahkan ganti file zip dengan yang berbeda yang berada di S3 bucket atau lokasi lain.
  ApplicationURL:
    Type: String
    Default: https://furqonmauladani.s3.ap-southeast-3.amazonaws.com/package.zip
    Description: Insert the URL where the software (package.zip) is located.

#----------------------------------------------------------------------------------------#
Resources:
# Buat EC2 instance dengan pilihan AMI, instance type, konfigurasi elastic network interface, IAM instance profile, keypair, user data, dan tag. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html.
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI sesuai dengan value dari System Manager - Parameter Store.
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
# Membuat elastic network interface dan mengatur agar menggunakan security group dan subnet yang dipilih oleh User.
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet: 
            - Ref: SecurityGroupID
          SubnetId:
            Ref: SubnetID
# Gunakan instance profile yang terhubung dengan IAM role yang dibuat (artinya EC2 memakai IAM role melalui instance profile).
      IamInstanceProfile:
        Ref: EC2ProfileforSSM
      UserData:
        Fn::Base64:
# User data bisa menggunakan variable dari parameter dengan notasi ${parameter} memanfaatkan Fn::Sub atau !Sub. Variable disini merupakan URL dari package aplikasi dalam format zip yang disimpan di S3 bucket atau server lainnya yang bisa diakses secara publik.
          Fn::Sub: |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install -y php7.2
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            usermod -a -G apache ec2-user
            chown -R ec2-user:apache /var/www
            chmod 2775 /var/www
            find /var/www -type d -exec chmod 2775 {} \;
            find /var/www -type f -exec chmod 0664 {} \;
            cd /var/www/html
            wget ${ApplicationURL}
            unzip package.zip
            rm -f package.zip
      Tags:
      - Key: Name
        Value:
          Fn::Sub: Lab - ${EC2Name}
      - Key: OS
        Value: Linux

# Buat elastic IP dan pasang ke EC2 instance. Public IPv4 address ini tidak akan berubah meskipun EC2 instance-nya dimatikan lalu dihidupkan. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html.
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: EC2
      Tags: 
      - Key: Name
        Value:
          Fn::Sub: Lab - ${EC2Name} EIP
  
# Buat IAM role yang membolehkan agar SSM agent didalam EC2 bisa dikontrol oleh AWS System Manager. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html.
  EC2RoleforSSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"
      Tags: 
      - Key: Name
        Value:
          Fn::Sub: Lab - ${EC2Name} Role

# Buat instance profile yang terhubung dengan IAM role. IAM role tidak akan dipasang secara langsung ke EC2 instance, melainkan instance profile yang akan dipasang. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html.
  EC2ProfileforSSM:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - Ref: EC2RoleforSSM

#----------------------------------------------------------------------------------------#
Outputs:
  EC2ID:
    Value:
      Ref: EC2
    Description: EC2 ID

  EC2PublicDNS:
    Value:
      Fn::GetAtt: EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2

  EC2PublicIP:
    Value:
      Fn::GetAtt: EC2.PublicIp
    Description: Public IPv4 of EC2

  EC2PrivateIP:
    Value:
      Fn::GetAtt: EC2.PrivateIp
    Description: Private IPv4 of EC2

# Membuat link untuk akses remote ke EC2 instance via System Manager - Session Manager. EC2 memiliki SSM agent dan IAM role yang cukup untuk melakukan akses remote.
  RemoteEC2:
    Value:
# Menggabungkan beberapa text untuk menampilkan link untuk akses remote, seperti:
# 1. URL System Manager - Session Manager yang sifatnya tidak berubah di region manapun.
# 2. ID dari EC2 yang ingin di remote. ID diambil dari EC2 yang dibuat.
# 3. Region ID yang akan berubah-berubah ketika template ini dieksekusi di region yang berbeda.
      Fn::Join: [ "", [ "https://console.aws.amazon.com/systems-manager/session-manager/", Ref: EC2, "?region=", Ref: AWS::Region ]]
    Description: Remote EC2 via System Manager - Session Manager