Description: >
  Membuat Linux EC2 dengan menggunakan AMI Amazon Linux 2 terbaru yang terdaftar di System Manager.
#----------------------------------------------------------------------------------------#
Parameters:
# User memilih System Manager - Parameter Store yang berisi AMI ID untuk EC2 instance, atau bisa menggunakan public Parameter Store yang berisi AMI ID Amazon Linux 2 terbaru. Harap gunakan AMI seperti Amazon Linux 2 yang sudah memiliki SSM agent terpasang didalamnya.
  AMI:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Select the Linux AMI ID inside System Manager - Parameter Store (The default value is the latest Amazon Linux 2 in public Parameter Store).

# User memilih InstanceType yang nanti digunakan oleh EC2 instance, atau bisa menggunakan default value.
  InstanceType:
    Type: String
    Default: t3a.micro
    AllowedValues:
      - t3a.nano
      - t3a.micro
      - t3a.small
    Description: Select instance type for EC2 instance. The default value is t3a.micro.

# User mengatur konfigurasi Subnet dan Security Group.
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select existing Subnet for EC2.
  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select existing SecurityGroup for EC2.

# User memasukkan nama EC2 yang akan digunakan melalui Tag.
  EC2Name:
    Type: String
    Default: MyEC2
    Description: Enter the name for this EC2.

# User memasukkan URL lokasi dimana aplikasi berada.
  ApplicationURL:
    Type: String
    Default: https://furqonmauladani.s3.amazonaws.com/package.zip
    Description: Insert the URL where the software (package.zip) is located.
#----------------------------------------------------------------------------------------#
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI sesuai dengan value dari Parameter Store.
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet: 
            - !Ref SecurityGroupID
          SubnetId: !Ref SubnetID
# Gunakan InstanceProfile yang terhubung dengan IAM Role yang dibuat (artinya EC2 memakai IAM Role melalui InstanceProfile).
      IamInstanceProfile: !Ref EC2ProfileforSSM
      UserData:
        Fn::Base64:
# UserData bisa menggunakan variable dari parameter dengan notasi ${parameter} memanfaatkan Fn::Sub atau !Sub.
          Fn::Sub: |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install -y php7.2
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            usermod -a -G apache ec2-user
            chown -R ec2-user:apache /var/www
            chmod 2775 /var/www
            find /var/www -type d -exec chmod 2775 {} \;
            find /var/www -type f -exec chmod 0664 {} \;
            cd /var/www/html
            wget ${ApplicationURL}
            unzip package.zip
            rm -f package.zip
      Tags:
      - Key: Name
        Value: !Sub Lab - ${EC2Name}
      - Key: OS
        Value: Linux

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2
      Tags: 
      - Key: Name
        Value: !Sub Lab - ${EC2Name} EIP
  
# Buat IAM Role yang membolehkan agar SSM agent di EC2 bisa dikontrol oleh AWS System Manager.
  EC2RoleforSSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"
      Tags: 
      - Key: Name
        Value: !Sub Lab - ${EC2Name} Role
# Buat InstanceProfile yang terhubung dengan IAM Role. IAM Role tidak akan dipasang secara langsung ke EC2 instance, melainkan InstanceProfile inilah yang akan dipasang.
  EC2ProfileforSSM:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - !Ref EC2RoleforSSM
#----------------------------------------------------------------------------------------#
Outputs:
  EC2PublicDNS:
    Value: !GetAtt EC2.PublicDnsName
    Description: Public DNS Endpoint of EC2
  EC2PublicIP:
    Value: !GetAtt EC2.PublicIp
    Description: Public IPv4 of EC2
  EC2PrivateIP:
    Value: !GetAtt EC2.PrivateIp
    Description: Private IPv4 of EC2
  RemoteEC2:
    Value:
# Menggabung beberapa text untuk menampilkan link untuk remote via System Manager - Session Manager.
      Fn::Join: [ "", [ "https://console.aws.amazon.com/systems-manager/session-manager/", !Ref EC2, "?region=", !Ref "AWS::Region" ]]
    Description: Remote EC2 via System Manager - Session Manager