Description: >
  Membuat EC2 baru dengan SecurityGroup dan ElasticIP. EC2 juga akan menggunakan Parameter (untuk InstanceType dan SSH keypair) dan Mapping (untuk AMI ID).

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
    Description: Enter instance type for EC2 instance. The default value is t3.micro.

  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

Mappings: 
  RegionMap: 
    us-east-1: 
      AmazonLinux: ami-04902260ca3d33422
    us-west-1: 
      AmazonLinux: ami-0d5075a2643fdf738
    eu-west-1: 
      AmazonLinux: ami-09ce2fc392a4c0fbc
    ap-southeast-1: 
      AmazonLinux: ami-03326c3f2f37e56a4
    ap-northeast-1: 
      AmazonLinux: ami-0404778e217f54308

Resources:
  DemoEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AmazonLinux]
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref SSHKey
# Pasang SecurityGroup yang dibuat dibawah.
      SecurityGroups:
        - !Ref DemoSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y php7.2
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
      Tags: 
      - Key: Name
        Value: DemoEC2
      - Key: OS
        Value: Amazon Linux 2

# Buat ElasticIP dan pasang ke EC2 instance yang dibuat.
  DemoEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DemoEC2
      Tags: 
      - Key: Name
        Value: DemoEIP

# Buat SecurityGroup yang membolehkan akses HTTP dan SSH untuk semua IP address.
  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all IP address to SSH and HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: DemoSecurityGroup

Outputs:
  EC2PublicDNS:
    Description: Public DNS Endpoint of EC2
    Value: !GetAtt DemoEC2.PublicDnsName
  EC2PublicIP:
    Description: Public IPv4 of EC2
    Value: !GetAtt DemoEC2.PublicIp
  EC2PrivateIP:
    Description: Private IPv4 of EC2
    Value: !GetAtt DemoEC2.PrivateIp