Description: >
  Membuat EC2 baru dengan SecurityGroup dan ElasticIP. EC2 juga akan menggunakan Parameter (untuk InstanceType dan SSH Keypair) dan Mapping (untuk AMI ID).

Parameters:
  InstanceType:
    Type: String
    Default: t3a.micro
    AllowedValues:
      - t3a.nano
      - t3a.micro
      - t3a.small
    Description: Select instance type for EC2 instance. The default value is t3a.micro.

  SSHKeypair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select existing EC2 KeyPair for remote SSH.

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
# Gunakan AMI ID milik Amazon Linux 2 terbaru dari public Parameter Store yang disediakan oleh AWS.
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: !Ref InstanceType
      KeyName: !Ref SSHKeypair
# Pasang SecurityGroup yang dibuat ke EC2 instance.
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
# Download dan extract halaman website kedalam EC2 instance.
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y php7.2
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          cd /var/www/html
          wget https://furqonmauladani.s3.amazonaws.com/package.zip
          unzip package.zip
          rm -f package.zip
      Tags: 
      - Key: Name
        Value: MyEC2
      - Key: OS
        Value: Amazon Linux 2

# Buat ElasticIP dan pasang ke EC2 instance yang dibuat.
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2
      Tags: 
      - Key: Name
        Value: MyEIP

# Buat SecurityGroup yang membolehkan akses HTTP dan SSH untuk semua IP address.
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all IP address to HTTP, SSH, and ICMP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: MySecurityGroup

# Ekstrak informasi EC2 instance yang dibuat. Public IPv4 atau public DNS-nya tetap berlaku, meskipun EC2-nya dimatikan dan dihidupkan karena EC2 menggunakan Elastic IP.
Outputs:
  EC2PublicDNS:
    Description: Public DNS Endpoint of EC2
    Value: !GetAtt EC2.PublicDnsName
  EC2PublicIP:
    Description: Public IPv4 of EC2
    Value: !GetAtt EC2.PublicIp
  EC2PrivateIP:
    Description: Private IPv4 of EC2
    Value: !GetAtt EC2.PrivateIp