Description: >
  Membuat EC2 yang terdaftar di SystemManager dengan menggunakan AMI Amazon Linux terbaru yang sudah terinstall SSM agent dan IAM Role yang memberikan permission ke agent supaya bisa komunikasi dengan AWS. EC2 juga memiliki SecurityGroup dan ElasticIP.

Parameters:
  AMIParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2
    Description: "Select the AMI for EC2 (The default is latest Amazon Linux 2)"

  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
    Description: Enter instance type for EC2 instance. Default value is t3.micro.

Resources:
  DemoEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIParameter
      InstanceType: !Ref InstanceTypeParameter
      IamInstanceProfile: !Ref DemoEC2ProfileforSSM
      SecurityGroups:
        - !Ref DemoSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><head><title>Hello Word</title></head><body><h1>Hello Cloudformation!</h1></body></html>" > /var/www/html/index.html
      Tags: 
      - Key: "Name"
        Value: "DemoEC2"
      - Key: "OS"
        Value: "Latest Amazon Linux 2"

  DemoEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DemoEC2
      Tags: 
      - Key: "Name"
        Value: "DemoEIP"
  
  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all IP address to SSH and HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      Tags: 
      - Key: "Name"
        Value: "DemoSecurityGroup"
  
  DemoEC2RoleforSSM:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"
      Tags: 
      - Key: "Name"
        Value: "DemoEC2RoleforSSM"
  DemoEC2ProfileforSSM:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - !Ref DemoEC2RoleforSSM
