Description: >
  RDS dengan pengaturan minimal.

#----------------------------------------------------------------------------------------#
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: DB Specification
      Parameters: [DatabaseName, InstanceClass, DBEngine]
    - Label:
        default: DB Credential
      Parameters: [Username, Password]

#----------------------------------------------------------------------------------------#
Parameters:
  Username:
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Description: Enter username of database admin.

  Password:
    Type: String
    MinLength: 8
    MaxLength: 30
    NoEcho: true
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must contain only alphanumberic characters with minimal 8 to 30 characters.
    Description: Enter password of database admin.

  InstanceClass:
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t3.small
      - db.t3.medium
    Description: Select instance class for DB instance. The default value is db.t2.micro.

  DBEngine:
    Type: String
    Default: MySQL
    AllowedValues:
      - MySQL
      - MariaDB
      - Postgres
      - SQLServer-EX
    Description: Select database engine for DB instance. The default value is MySQL.

  DatabaseName:
    Type: String
    Default: MyRDS
    Description: Enter the name for this DB instance.

#----------------------------------------------------------------------------------------#
Resources:
# Buat RDS MySQL. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html.
  RDS:
    Type: AWS::RDS::DBInstance
# Ketika CloudFormation stack didelete, semua resource akan didelete. DeletionPolicy memastikan resource didelete ketika CloudFormation stack didelete, tanpa melakukan snapshot. Hal ini dikarenakan DB instance secara default akan melakukan snapshot sebelum resource didelete. Bisa juga diganti "Snapshot" untuk memastikan resource disnapshot sebelum didelete, atau "Retain" untuk memastikan resource tidak didelete meskipun stacknya didelete. Informasi lebih lanjut ada disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html.
    DeletionPolicy: Delete
    Properties:
# Gunakan nama DB instance yang dipilih oleh user.
      DBInstanceIdentifier:
        Ref: DatabaseName
# Kapasitas storage untuk database (dalam satuan GB) dengan nilai minimal 20 sampai 65536, kecuali untuk SQL Server harus 16384. Jika menggunakan provisioned IOPS SSD harus diisi minimal 100.
      AllocatedStorage: 100
      BackupRetentionPeriod: 7
      DBInstanceClass:
        Ref: InstanceClass
      Engine:
        Ref: DBEngine
      MasterUsername:
        Ref: Username
      MasterUserPassword:
        Ref: Password
# Mengatur apakah menggunakan single node saja, atau 2 node untuk availability.
      MultiAZ: false
# Membuat DB instance bisa diakses via internet.
      PubliclyAccessible: true
# Hapus tanda komentar "#" kalau ingin menggunakan provision IOPS SSD.
    # Iops: '1000'
      Tags:
      - Key: Name
        Value:
          Fn::Sub: Lab - ${DatabaseName} Instance

#----------------------------------------------------------------------------------------#
Outputs:
# Ekstrak informasi DNS endpoint dan port milik DB instance.
  ConnectionString:
    Value:
      Fn::Join: [":", [Fn::GetAtt: [RDS,Endpoint.Address], Fn::GetAtt: [RDS,Endpoint.Port]]]
    Description: Database connection string