Description: >
  DynamoDB table dengan primary key (hash key dan range key).

#----------------------------------------------------------------------------------------#
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Partition Key (Hash Key)
      Parameters: [Attribute1, Attribute1Type]
    - Label:
        default: Sort Key (Range Key)
      Parameters: [Attribute2, Attribute2Type]
    - Label:
        default: RCU/WCU
      Parameters: [ReadCapacityUnits, WriteCapacityUnits]

    ParameterLabels:
      Attribute1:
        default: Name of hash key.
      Attribute1Type:
        default: Type of hash key. Input string (S), or number (N).
      Attribute2:
        default: Name of range key.
      Attribute2Type:
        default: Type of range key. Input string (S), or number (N).
      ReadCapacityUnits:
        default: Provision Read Capacity Units (1 RCU is 4KB/s throughput for read).
      WriteCapacityUnits:
        default: Provision Write Capacity Units (1 WCU is 1KB/s throughput for write).

#----------------------------------------------------------------------------------------#
Parameters:
# User menentukan beberapa atribut dari DynamoDB table. Atribut mirip dengan kolom jika dibandingkan dengan relational database.
  Attribute1:
    Type: String
    AllowedPattern: "[a-zA-Z0-9]*"
    MinLength: 1
    MaxLength: 2048
    ConstraintDescription: Must contain only alphanumberic characters.

  Attribute2:
    Type: String
    AllowedPattern: "[a-zA-Z0-9]*"
    MinLength: 1
    MaxLength: 2048
    ConstraintDescription: Must contain only alphanumberic characters.

# User menentukan tipe atributnya apakah string atau number untuk setiap atribut.
  Attribute1Type:
    Type: String
    Default: S
    AllowedPattern: "[S|N]"
    ConstraintDescription: Must be either S, or N.

  Attribute2Type:
    Type: String
    Default: S
    AllowedPattern: "[S|N]"
    ConstraintDescription: Must be either S, or N.

# Atur kemampuan baca database per detik DynamoDB table. Nilai 1 RCU = 4 KB/s. Jadi kalau 100 RCU maka table mendapatkan throughput sebesar 400 KB/s.
  ReadCapacityUnits:
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 10000
    ConstraintDescription: Must be between 5 and 10000.

# Atur kemampuan tulis database per detik DynamoDB table. Nilai 1 RCU = 1 KB/s. Jadi kalau 100 RCU maka table mendapatkan throughput sebesar 100 KB/s.
  WriteCapacityUnits:
    Type: Number
    Default: 10
    MinValue: 5
    MaxValue: 10000
    ConstraintDescription: Must be between 5 and 10000.

#----------------------------------------------------------------------------------------#
Resources:
# Buat database DynamoDB dengan hash key dan range key. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html.
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
# Atur beberapa atribut dari DynamoDB table.
      AttributeDefinitions:
      - AttributeName:
          Ref: Attribute1
        AttributeType:
          Ref: Attribute1Type
      - AttributeName:
          Ref: Attribute2
        AttributeType:
          Ref: Attribute2Type
# Atur primary key yang terdiri dari partition key (hash key) dan sort key (range key).
      KeySchema:
      - AttributeName:
          Ref: Attribute1
        KeyType: HASH
      - AttributeName:
          Ref: Attribute2
        KeyType: RANGE
# Atur kemampuan baca dan tulis database per detik sesuai dengan yang dimasukkan oleh user.
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits

#----------------------------------------------------------------------------------------#
Outputs:
# Ekstrak informasi nama DynamoDB table yang diperlukan untuk akses ke database.
  TableARN:
    Value:
      Ref: DynamoDBTable
    Description: DynamoDB table name