Description: >
  Membuat 2 VPC yang berbeda dengan memanfaatkan 1 template VPC yang lain.

Parameters:
  MyFirstVPC:
    Description: Please enter the name for first VPC
    Type: String
    Default: MyVPC1
  MySecondVPC:
    Description: Please enter the name for second VPC
    Type: String
    Default: MyVPC2

Resources:
  VPC1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/5.1-vpc-multiaz.yaml
      Parameters:
        VPCName: !Ref MyFirstVPC
        VPCCIDR: 192.168.0.0/16
        PublicSubnet1CIDR: 192.168.0.0/24
        PrivateSubnet1CIDR: 192.168.1.0/24
        PublicSubnet2CIDR: 192.168.2.0/24
        PrivateSubnet2CIDR: 192.168.3.0/24

  VPC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/5.1-vpc-multiaz.yaml
      Parameters:
        VPCName: !Ref MySecondVPC
        VPCCIDR: 172.31.0.0/16
        PublicSubnet1CIDR: 172.31.0.0/24
        PrivateSubnet1CIDR: 172.31.1.0/24
        PublicSubnet2CIDR: 172.31.2.0/24
        PrivateSubnet2CIDR: 172.31.3.0/24
