Description: >
  AutoScaling Linux EC2 with ALB.

#----------------------------------------------------------------------------------------#
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3a.small
      - t3a.medium
    Description: Select instance type for EC2 instance. The default value is t2.micro.

  FirstEC2SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select the first Subnet ID where the EC2 instances.
  SecondEC2SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select the second Subnet ID where the EC2 instances.
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID.
  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select existing SecurityGroup for EC2 instance.

#----------------------------------------------------------------------------------------#
Resources:
  AutoScalingGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/7.0-autoscaling.yaml
      Parameters:
        InstanceType:
          Ref: InstanceType
        TargetGroupARN:
          Fn::GetAtt: [ApplicationLoadBalancer,Outputs.TargetGroupID]
        FirstEC2SubnetID:
          Ref: FirstEC2SubnetID
        SecondEC2SubnetID:
          Ref: SecondEC2SubnetID      
        SecurityGroupID:
          Ref: SecurityGroupID

  ScalingPolicySchedule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/7.1-scaling-policy-schedule.yaml
      Parameters:
        AutoScalingGroupID:
          Fn::GetAtt: [AutoScalingGroup,Outputs.AutoScalingGroupID]

  ScalingPolicySimple:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/7.2-scaling-policy-simplescaling.yaml
      Parameters:
        AutoScalingGroupID:
          Fn::GetAtt: [AutoScalingGroup,Outputs.AutoScalingGroupID]

  ApplicationLoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://furqonmauladani.s3.amazonaws.com/6.0-alb.yaml
      Parameters:
        FirstEC2SubnetID:
          Ref: FirstEC2SubnetID
        SecondEC2SubnetID:
          Ref: SecondEC2SubnetID      
        VPCID:
          Ref: VPCID

#----------------------------------------------------------------------------------------#
Outputs:
  WebsiteURL:
    Value:
      Fn::GetAtt: [ApplicationLoadBalancer,Outputs.URL]
    Description: URL of the website