Description: >
  Microsoft Active Directory menggunakan Directory Service.
# Directory Service adalah AWS Managed Microsoft Active Directory (AD). Informasi lebih lanjut ada disini https://aws.amazon.com/directoryservice.

#----------------------------------------------------------------------------------------#
Parameters:
# User memasukkan nama domain untuk Microsoft Active Directory.
  ActiveDirectoryName:
    Type: String
    Default: trainocate.nusa
    Description: Name of Directory Service.

# User mengatur konfigurasi VPC, subnet dan security group.
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID.

  SubnetID1:
    Type: AWS::EC2::Subnet::Id
    Description: Select the first Private Subnet.

  SubnetID2:
    Type: AWS::EC2::Subnet::Id
    Description: Select the second Private Subnet.

#----------------------------------------------------------------------------------------#
Resources:
# Buat directory service yang merupakan managed Microsoft Active Directory dari AWS. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-microsoftad.html.
  DirectoryService: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
        Name:
          Ref: ActiveDirectoryName
        Edition: Standard
# Atur password untuk Microsoft Active Directory menggunakan data dari System Manager - Parameter Store. Jika sudah ada parameter sebelumnya, silahkan ganti nama parameter dibawah dengan parameter yang dipunya. Namun jika belum punya, maka silahkan buat parameter dengan nama "/microsoft/active-directory/password". Karena paramater digunakan untuk password, maka rekomendasinya menggunakan SecureString.
        Password: '{{resolve:ssm-secure:/microsoft/active-directory/password}}'
        VpcSettings: 
          SubnetIds: 
            - Ref: SubnetID1
            - Ref: SubnetID2
          VpcId:
            Ref: VPCID

# Buat SSM document untuk join ke Microsoft Active Directory. Rincian propertinya bisa lihat disini https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html.
  JoinADDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: (Required) The ID of the AWS Directory Service directory.
          directoryName:
            type: String
            description: (Required) The name of the directory, for example trainocate.internal
          dnsIpAddresses:
            type: StringList
            default: []
            description: (Optional) The IP addresses of the DNS servers in the directory. Required when DHCP is not configured.
            allowedPattern: "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
        runtimeConfig:
          aws:domainJoin:
            properties:
              directoryId: "{{ directoryId }}"
              directoryName: "{{ directoryName }}"
              dnsIpAddresses: "{{ dnsIpAddresses }}"

#----------------------------------------------------------------------------------------#
Outputs:
# Ekstrak informasi nama dan ID dari directory service.
  DirectoryServiceID:
    Value:
      Ref: DirectoryService
    Description: ID of Directory Service

  DirectoryServiceName:
    Value:
      Ref: ActiveDirectoryName
    Description: Name of Directory Service

# Ekstrak informasi nama dari SSM document.
  JoinADDocumentName:
    Value:
      Ref: JoinADDocument
    Description: Name of System Manager - Document for join directory

# Ekstrak informasi IP address dari directory service.
  DirectoryIPAddress1:
    Value:
      Fn::Select: [0, Fn::GetAtt: DirectoryService.DnsIpAddresses]
    Description: The first IP address for a directory

  DirectoryIPAddress2:
    Value:
      Fn::Select: [1, Fn::GetAtt: DirectoryService.DnsIpAddresses]
    Description: The second IP address for a directory