Description: >
  Membuat Directory Service yang merupakan managed Microsoft Active Directory.

#----------------------------------------------------------------------------------------#
Parameters:
# User memasukkan nama domain untuk Microsoft Active Directory di Directory Service.
  ActiveDirectoryName:
    Type: String
    Default: trainocate.nusa
    Description: Name of Directory Service.

# User mengatur konfigurasi VPC, Subnet dan Security Group.
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID.

  SubnetID1:
    Type: AWS::EC2::Subnet::Id
    Description: Select the first Private Subnet.

  SubnetID2:
    Type: AWS::EC2::Subnet::Id
    Description: Select the second Private Subnet.

#----------------------------------------------------------------------------------------#
Resources:
# Buat Directory Service yang merupakan managed Microsoft Active Directory.
  DirectoryService: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
        Name:
          Ref: ActiveDirectoryName
        Edition: Standard
        Password: '{{resolve:ssm-secure:/microsoft/active-directory/password}}'
        VpcSettings: 
          SubnetIds: 
            - Ref: SubnetID1
            - Ref: SubnetID2
          VpcId:
            Ref: VPCID

# Buat SSM Document untuk join ke managed Microsoft Active Directory.
  JoinADDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: (Required) The ID of the AWS Directory Service directory.
          directoryName:
            type: String
            description: (Required) The name of the directory, for example trainocate.internal
          dnsIpAddresses:
            type: StringList
            default: []
            description: (Optional) The IP addresses of the DNS servers in the directory. Required when DHCP is not configured.
            allowedPattern: "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
        runtimeConfig:
          aws:domainJoin:
            properties:
              directoryId: "{{ directoryId }}"
              directoryName: "{{ directoryName }}"
              dnsIpAddresses: "{{ dnsIpAddresses }}"

#----------------------------------------------------------------------------------------#
Outputs:
# Ekstrak informasi nama dan ID dari Directory Service yang dibuat.
  DirectoryServiceID:
    Value:
      Ref: DirectoryService
    Description: ID of Directory Service

  DirectoryServiceName:
    Value:
      Ref: ActiveDirectoryName
    Description: Name of Directory Service

# Ekstrak informasi ID dari System Manager - Document untuk join ke Domain Service.
  JoinADDocumentID:
    Value:
      Ref: JoinADDocument
    Description: ID of System Manager - Document for join directory

# Ekstrak informasi IP address dari Directory Service yang dibuat.
  DirectoryIPAddress1:
    Value:
      Fn::Select: [0, Fn::GetAtt: DirectoryService.DnsIpAddresses]
    Description: The first IP address for a directory

  DirectoryIPAddress2:
    Value:
      Fn::Select: [1, Fn::GetAtt: DirectoryService.DnsIpAddresses]
    Description: The second IP address for a directory